### ISSUE TITLE
Take profit : how ?

### ISSUE THREAD

**Issue by Fab5414** [icastillejogomez/degiro-api#10]
Hello,

If I want to close one of my orders (and so take profit), what should I do in the order param ? 
Should I make a Sell Order with "Stop Loss" without indicate the order id ?
And, if I want to sell 50% of my position ?

I don't want a "short order"....

Thanks

**Comment by icastillejogomez** [comment]
Create a SELL order with the type you want (market, limit, stoploss, stop limit)

If you want to sell the half position, in `size` param set the half amount of stock you bought
