### ISSUE TITLE
Requesting all the account transactions

### ISSUE THREAD

**Issue by KenVanGilbergen** [icastillejogomez/degiro-api#14]
I am trying to find a way to retrieve all the transactions of an account, not only the orders but also the fees, dividends, ... 
Not sure if this is current possible?
> https://trader.degiro.nl/reporting/secure/v6/accountoverview

**Comment by icastillejogomez** [comment]
Which methods of the library did you tried?

**Comment by Chavithra** [comment]
Hello guys,

this link from @KenVanGilbergen appends to be an endpoint : 

https://trader.degiro.nl/reporting/secure/v6/accountoverview

This endpoint seems to be handled by this library, with the following method :
- getAccountState

Hope that helps

**Comment by brambekkers** [comment]
Maybe you can tell in the docs that the option is necessary to include. Mation that the date object must be an object with two strings like this: {
                     from: '01/01/2000 ',
                     to: '28/02/2021'
                 }

**Comment by romainsimon** [comment]
Thanks @brambekkers this works fine :

```js
const transactions = await degiro.getAccountState({
    from: '01/01/2000',
    to: '28/02/2021'
})
console.log(transactions)
```
