### ISSUE TITLE
Have to re-enter credentials even when jsessionid is available.

### ISSUE THREAD

**Issue by danielvandenberg95** [icastillejogomez/degiro-api#15]
I'd like to not prompt my users for username/password if there's still a jsessionid available. However, there's currently an explicit check to verify that an username and password are given.

Is there a reason this check exists (as I'm assuming degiro would check this server-side too), or is it double?

Should the check be removed, stay in place (for a reason unknown to me) and have documentation added, or can the check be wrapped in a ```if (!this.jsessionId)```?

**Comment by magnific0** [comment]
@danielvandenberg95 this is fixed this in #21 and in the newest version on npm (v1.0.3). 

Any smart prompting should probably take place on the application level, but the library now requires either username/password to be set OR a jsessionid. 

I'm new to this library and degiro. So in your experienc, how long do jsessionids remain valid. Can you refresh them?

**Comment by icastillejogomez** [comment]
@magnific0 Do we close this issue then?

**Comment by magnific0** [comment]
@icastillejogomez sounds fine with me. I assume @danielvandenberg95 took note, so let's call it resolved.
