### ISSUE TITLE
searchProduct returns undefined instead of empty array when unknown search string.

### ISSUE THREAD

**Issue by danielvandenberg95** [icastillejogomez/degiro-api#16]
When searching for "searchProduct" I get undefined instead of an empty array. Working around it with ```searchProduct(...) || []``` for now.

**Comment by icastillejogomez** [comment]
Do you have a pull request for that?

**Comment by icastillejogomez** [comment]
Something like that https://github.com/icastillejogomez/degiro-api/pull/26 ?

**Comment by danielvandenberg95** [comment]
Looks great!

**Comment by icastillejogomez** [comment]
Can you publish a release to npm registry or only I can do? You should be able to do it
