### ISSUE TITLE
401 error on login

### ISSUE THREAD

**Issue by brambekkers** [icastillejogomez/degiro-api#23]
Ill get a VM24392:1 GET https://trader.degiro.nl/login/secure/config 401 error on login().

`const degiro = new DeGiro({
	username: this.username,
	pwd: this.pwd,
	oneTimePassword: this.oneTimePassword,
});

try {
	await degiro.login();
	const jsessionId = degiro.getJSESSIONID();
	console.log(jsessionId);
} catch (error) {
	console.log(error);
}`

**Comment by danielvandenberg95** [comment]
Hi @brambekkers,

Unfortunately this is not enough information for us to view this as a bug. The reason for this is that 401 is an "unauthorized" error, which you would get if your credentials are incorrect, and for others (me, in any case) the login function does work.

Can you verify the following:
 - Using e.g. console.log, verify that this.username, this.pwd and this.oneTimePassword are correct.
 - Ensure that you did not use this specific oneTimePassword before. Using the same OTP multiple times will cause a 401.
 - Print the result of ```await degiro.login()```.

**Comment by brambekkers** [comment]
I just got it working in NodeJS. I can't get it working on the cliend side. It seems to be blocked by Cors policy.

**Comment by danielvandenberg95** [comment]
It's good that you mention it, I've ran into the same issue once too. Unfortunately CORS can't (and shouldn't) be circumvented, and as such the readme would be incorrect. Because of this this is not a front-end library...

**Comment by icastillejogomez** [comment]
Sorry guys, when I prepared the code to run in the web browser I was able to log into the platform.

It makes sense for CORS to block access. We just updated Readme.md file

**Comment by icastillejogomez** [comment]
Trying from a backend It works?

**Comment by brambekkers** [comment]
Thanks for the update, the backend works perfectly!

**Comment by icastillejogomez** [comment]
Awesome! So we can close this issue. Thank you all for being here adding value to this project!!
