### ISSUE TITLE
Real time degiro data

### ISSUE THREAD

**Issue by stam** [icastillejogomez/degiro-api#27]
Hey hey,
This isn't an issue but a question.
First of all thanks for the great api!

I was wondering if there are any plans to include the real time price updates in this api.
I want to get realtime updates for my positions, including options on the Amsterdam exchange, which a lot of data providers don't have.

I was looking to implement this myself, but I don't even see a websocket or anything the degiro app is fetching data from.
There is no open websocket, no service worker data, nothing.

Do you have any idea how to reverse engineer this?

**Comment by icastillejogomez** [comment]
I also looked at it and degiro gets real time from vwd. I recommend you get the market prices from another provider. I use iexcloud. Do you know him?

**Comment by stam** [comment]
Yeah I also use iexcloud, but amsterdam options support is abysmal. 
I'll probably use euronext data directly or derive options price using black scholes.

I'm still puzzled on the engineering aspect of degiro though, real time updates without websockets or serviceworkers.
Am I missing an xhr longpolling request somewhere?

**Comment by inacioc** [comment]
Dear All,

Does you know real time providers from Euronext stock and indexes (CAC 40, DAX 30,etc)?
Does iexcloud provide it?

Best Regards,
Inacio CARVALHO

**Comment by icastillejogomez** [comment]
I don't
