### ISSUE TITLE
this pile of crap dont work none!

### ISSUE THREAD

**Issue by bitministry** [icastillejogomez/degiro-api#4]
even your example code dont work.

TypeError: DeGiro is not a constructor

**Comment by icastillejogomez** [comment]
Could you share the code you tried?

**Comment by bitministry** [comment]
const DeGiro = require('degiro-api')

// Basic degiro init
const degiro = new DeGiro({
  username: '<your_username_here>',
  pwd: '*****'
})

**TypeError: DeGiro is not a constructor**

// or creating with the static create method
const degiro = DeGiro.create({ username: '*****', pwd: '*****' })


**create is not a method**

**Comment by icastillejogomez** [comment]
const DeGiro = require('degiro-api').DeGiro

**Comment by bitministry** [comment]
**undefined**

dude, why u posting this BS.. cant u try it yourself before u make a recommendation?

**Comment by bitministry** [comment]
ok , i actually found a way..
_const DeGiro = require('degiro-api').default;_

u may want to update your tutorial ;)

**Comment by icastillejogomez** [comment]
Dude, you could be more respectful or develop the api yourself. You could use typescript or print the module import. Bye!!
