### ISSUE TITLE
Docs question: can you elaborate a bit more about sessions and OTP?

### ISSUE THREAD

**Issue by AppElent** [icastillejogomez/degiro-api#45]
Hi,

I love this project! 
Can you elaborate a bit more about the sessionID? Is it just a token that I should store in nodejs memory or whatever for every person that wants to authenticate? So:
- Session id is user bound?
- Why do you get this session ID from env variable (this will never be an env variable right? Because it is session based)

Questions about OTP:
- The OTP normally is valid for a few seconds. How do you deal with that when relogin? I dont want to have the user to enter the info every time.

**Comment by icastillejogomez** [comment]
As degiro doesn't provide a server-to-server auth system you need to handle this scenarios requesting user to login again if needed. If you want to make a better explanation in the README.md file we're open to accept a pull request for that
