### ISSUE TITLE
Credentials are only taken from env vars

### ISSUE THREAD

**Issue by luixal** [icastillejogomez/degiro-api#47]
Hi,

I tried to make this code work:

```js
const DeGiro = require('degiro-api').default

const username = 'myUsername';
const password = 'myPassword';

const degiro = new DeGiro({ username, password });

(async() => {
  console.log(`Logging in as ${process.env.DEGIRO_USER}...`);
  const data = await degiro.login();

  const jsessionId = degiro.getJSESSIONID();
  console.log(`Logged. Session ID: ${jsessionId}`);
  console.log(data);
})()
```

and got and error telling me that login needed credentials:

```
Error: DeGiro api needs an password to access
```

I got the same error when using the `create` function.

The only way I've made it work is by using env vars DEGIRO_USER and DEGIRO_PWD.

Any idea about how to make it work with constructor params?

Thanks!

**Comment by danielvandenberg95** [comment]
Hi luixal,

I see that this question is answered in an example at the readme. I'd recommend starting with the examples there, and changing as little as possible, one step at a time.

**Comment by luixal** [comment]
Hi @danielvandenberg95 ,

I always get started with the examples. I took this code from the readme:

```js
// Basic degiro init
const degiro = new DeGiro({
  username: '<your_username_here>',
  pwd: '*****'
})

// or creating with the static create method
const degiro = DeGiro.create({ username: '*****', pwd: '*****' })

// or create with env credentials
const degiro = new DeGiro() // <-- Use DEGIRO_USER & DEGIRO_PWD
```

The first two ways throw that error about the need for a password, only the last example works for me.

Do you have any code that works for you passing `username` and `password` as params?

Thanks!

**Comment by luixal** [comment]
Just closing this as it was totally my stupidity mixing param names.

Sorry!
