### ISSUE TITLE
How to get maximum order size

### ISSUE THREAD

**Issue by Earu** [icastillejogomez/degiro-api#52]
For some securities there is a maximum order size allowed by degiro, it returns an error via check `checkOrder` like so:
```
The maximum quantity for market orders on this product is 68. To place an order with a higher quantity, please use the limit order.
```

Of course I could use a limit order but this is quite annoying, is there a way to figure out the maximum order size somehow?

**Comment by icastillejogomez** [comment]
I did found any relevant endpoint to get this data before the order creation. If you found an endpoint to get this information we can implement it on this library. For the moment I'm going to close this issue feel free to re-open it if needed.
