### ISSUE TITLE
Values from Account Summary (Closed issue; can not find the answer).

### ISSUE THREAD

**Issue by BobKooistra** [icastillejogomez/degiro-api#53]
Hi icastillejogomez (and soltex1),
Please see the closed issue: "Values from Account Summary" from soltex1
I have the same question as asked in this closed issue.
Can you share the answer or solution to this question?
Or can you indicate where the answer can be found?
I have no idea where to look.
Thank you in advance.

**Comment by icastillejogomez** [comment]
Duplicated https://github.com/icastillejogomez/degiro-api/issues/34
